#define AvVersion                  "20260124"
#define GSV6K5                     1
#define GSV6505                    1
#define Gsv6k5MuxMode              0
#define Gsv6k5AudioBypass          0
#define Gsv6k5AviInfoBypass        0
#define Gsv6k5AudioInfoBypass      0
#define Gsv6k5VsInfoBypass         0
#define Gsv6k5SpdInfoBypass        0
#define Gsv6k5MpegInfoBypass       0
#define Gsv6k5HdrInfoBypass        0
#define Gsv6k5IsrcPktBypass        0
#define Gsv6k5AcpPktBypass         0
#define Gsv6k5GmdPktBypass         0
#define Gsv6k5EmpPktBypass         1
#define Gsv6k5AmdPktBypass         0
#define AvForceDefaultEdid         1
#define AvStrictEdidRule           1
#define AvEdidMaxSize              512
#define AvEnableCecFeature         0
#define AvCecLinkageMode           1
#define AvCecMessageEvent          AvEnableCecFeature
#define AvCecDataReadingInEvent    AvEnableCecFeature
#define AvCecDataSendingOutEvent   AvEnableCecFeature
#define AvCecGsvVendorIdByte1      0xa5
#define AvCecGsvVendorIdByte2      0xa5
#define AvCecGsvVendorIdByte3      0xa5
#define AvCecPortIndex             4
#define AvCecLogicAddress          0x5
#define AvEnableAudioTTLInput      1
#define AvEnableInternalVideoGen   1
#define AvEnableInternalAudioGen   0
#define AvEnableInternalClockGen   0
#define AvEnableHdcp2p2Feature     1
#define AvEnableUartInput          1
#define AvEnableDebugMessage       1
#define AvEnableDebugHdcp          0
#define AvEnableDebugFsm           1
#define AvEnableIntegrityCheck     0
#define AvEnableKeyInput           0
#define AvEnableMailbox            0
#define AvKeyDelayThreshold        1
#define AvIrdaFunctionInput        0
#define RxHpdDelayExpireThreshold  50
#define RxLockDelayExpireThreshold 1
#define RxEQDelayExpireThreshold   250
#define RxFrlLockExpireThreshold   250
#define TxHpdDelayExpireThreshold  1
#define TxVideoManageThreshold     3
#define TxAudioManageThreshold     3
#define TxScdcManageThreshold      50
#define TxHdcpManageThreshold      150
#define TxCecManageThreshold       150
#define AvDontCareEdidSpa          1
#define AvNoLinkageMode            1
#define AvAllowHpdLowEdidRead      0
#define AvEnableDetailTiming       1
#define AvHdcpRxErrorThreshold     10
#define AvHdcpTxErrorThreshold     5
#define AvEdidStoredInRam          1
#define AvEdidSameNoAcknowledge    1
#define AvEdidErrorThreshold       200
#define AvEnableHdcp1p4BksvCheck   0
#define AvEnableTxScdcCedCheck     0
#define AvEnableTxCtsPhySetting    1
#define AvEnableTxCtsFrlTraining   0
#define AvEnableEarcRxCts          1
#define AvEnableCecCts             0
#define AvEnableTmdsRxCts          0
#define AvEnableTmdsTxCts          0
#define AvEnableConsistentFrl      0
#define AvEnableEArcTxFeature      0
#define AvEnableEArcRxFeature      0
#define AvEnableTxSingleLaneMode   0
#define AvEnableRxSingleLaneMode   0
#define AvEnableSpdifToI2s         0
#define AvEnableI2sDualDirection   0
#define AvUseSpdifOutOnI2sData0    0
#define AvEnableTTLCompressAudio   0
#define AvEnableFrl48GSupport      1
#define AvEnableDualFrlOutRate     0
#define AvEnableThumbnail          0

#define AvEnableDebugMode          0


#define Gsv6k5DeviceNumber         2
#define Gsv6k5DeviceIndexOffset    0
#define Gsv6k5PortNumber           (8+AvEnableInternalVideoGen+AvEnableAudioTTLInput)



#define Gsv6kResourceSize          (Gsv6k5ResourceSize*Gsv6k5DeviceNumber)

