#ifndef GSV6K5_TXFRL_MAP_FCT_H
#define GSV6K5_TXFRL_MAP_FCT_H
#define GSV6K5_TXFRL_set_FRL_CTRL_MAN_EN(port, val)                     AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x00, 0x10, 0x4, val)
#define GSV6K5_TXFRL_get_FRL_RATE(port, pval)                           AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x00, 0xF, 0, pval)
#define GSV6K5_TXFRL_set_FRL_RATE(port, val)                            AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x00, 0xF, 0, val)
#define GSV6K5_TXFRL_set_FRL_MODE_EN(port, val)                         AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x01, 0x10, 0x4, val)
#define GSV6K5_TXFRL_get_FRL_LANE_NUM(port, pval)                       AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x01, 0xF, 0, pval)
#define GSV6K5_TXFRL_set_FRL_LANE_NUM(port, val)                        AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x01, 0xF, 0, val)
#define GSV6K5_TXFRL_get_FRL_DATA_RATE(port, pval)                      AvHalI2cReadField32BE(GSV6K5_TXFRL_MAP_ADDR(port), 0x02, 0xFF, 0xFF, 0, 2, pval)
#define GSV6K5_TXFRL_set_FRL_DATA_RATE(port, val)                       AvHalI2cWriteField32BE(GSV6K5_TXFRL_MAP_ADDR(port), 0x02, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_TXFRL_set_FRL_TRAIN_FSM_DISABLE(port, val)               AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x05, 0x40, 0x6, val)
#define GSV6K5_TXFRL_get_FRL_SKIP_ALL_DDC(port, pval)                   AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x05, 0x10, 0x4, pval)
#define GSV6K5_TXFRL_set_FRL_SKIP_ALL_DDC(port, val)                    AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x05, 0x10, 0x4, val)
#define GSV6K5_TXFRL_set_FRL_SKIP_TRAINING(port, val)                   AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x05, 0x1, 0x0, val)
#define GSV6K5_TXFRL_set_FRL_WT_FLT_READY_TIMER(port, val)              AvHalI2cWriteField32BE(GSV6K5_TXFRL_MAP_ADDR(port), 0x06, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_TXFRL_set_FRL_WT_FLT_UPDATE_TIMER(port, val)             AvHalI2cWriteField32BE(GSV6K5_TXFRL_MAP_ADDR(port), 0x08, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_TXFRL_set_FRL_WT_FRL_START_TIMER(port, val)              AvHalI2cWriteField32BE(GSV6K5_TXFRL_MAP_ADDR(port), 0x0A, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_TXFRL_get_RB_FRL_TRAINING_PASS(port, pval)               AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x0C, 0x20, 0x5, pval)
#define GSV6K5_TXFRL_set_FRL_MAN_TX_SEND_GAP_EN(port, val)              AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x19, 0x20, 0x5, val)
#define GSV6K5_TXFRL_set_FRL_MAN_TX_SEND_VID_EN(port, val)              AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x19, 0x10, 0x4, val)
#define GSV6K5_TXFRL_set_FRL_MAN_LN0_LTP_REQ(port, val)                 AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x1A, 0xF0, 4, val)
#define GSV6K5_TXFRL_set_FRL_MAN_LN1_LTP_REQ(port, val)                 AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x1A, 0xF, 0, val)
#define GSV6K5_TXFRL_set_FRL_MAN_LN2_LTP_REQ(port, val)                 AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x1B, 0xF0, 4, val)
#define GSV6K5_TXFRL_set_FRL_MAN_LN3_LTP_REQ(port, val)                 AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x1B, 0xF, 0, val)
#define GSV6K5_TXFRL_set_FRL_TIMING_DET_RESTART(port, val)              AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x23, 0x80, 0x7, val)
#define GSV6K5_TXFRL_set_FRL_TMDS_HBLANK_MAN_EN(port, val)              AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x23, 0x10, 0x4, val)
#define GSV6K5_TXFRL_set_FRL_HTOTAL_STABLE_MAN_EN(port, val)            AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x23, 0x8, 0x3, val)
#define GSV6K5_TXFRL_set_FRL_FIFO_TH_VALUE_MAN_EN(port, val)            AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x2D, 0x40, 0x6, val)
#define GSV6K5_TXFRL_set_FRL_VID_FIFO_TH_MAN_VALUE(port, val)           AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x2F, 0xFF, 0, val)
#define GSV6K5_TXFRL_set_FRL_BLK_FIFO_TH_MAN_VALUE(port, val)           AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x30, 0xFF, 0, val)
#define GSV6K5_TXFRL_set_FRL_REPCNT_BYPASS(port, val)                   AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x34, 0x2, 0x1, val)
#define GSV6K5_TXFRL_set_FRL_TX_FIFO_MANUAL_RST(port, val)              AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x35, 0x20, 0x5, val)
#define GSV6K5_TXFRL_set_FRL_TX_LANE_FIFO_RST(port, val)                AvHalI2cWriteField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x3B, 0x8, 0x3, val)
#define GSV6K5_TXFRL_get_RB_FRL_XTAL_HBLANK_VALID(port, pval)           AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x63, 0x8, 0x3, pval)
#define GSV6K5_TXFRL_get_RB_FRL_VIDEO_FIFO_TH(port, pval)               AvHalI2cReadField8(GSV6K5_TXFRL_MAP_ADDR(port), 0x6D, 0xFF, 0, pval)
#endif
