#ifndef GSV6K5_VSP_MAP_FCT_H
#define GSV6K5_VSP_MAP_FCT_H
#define GSV6K5_VSP_get_DG_VID(port, pval)                             AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x00, 0xFF, 0, pval)
#define GSV6K5_VSP_set_DG_VID(port, val)                              AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x00, 0xFF, 0, val)
#define GSV6K5_VSP_get_DG_EN(port, pval)                              AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x01, 0x80, 0x7, pval)
#define GSV6K5_VSP_set_DG_EN(port, val)                               AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x01, 0x80, 0x7, val)
#define GSV6K5_VSP_get_DG_PATTERN(port, pval)                         AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x01, 0x7C, 2, pval)
#define GSV6K5_VSP_set_DG_PATTERN(port, val)                          AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x01, 0x7C, 2, val)
#define GSV6K5_VSP_set_DG_PARAM_MAN_EN(port, val)                     AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x01, 0x2, 0x1, val)
#define GSV6K5_VSP_set_DG_V_POL(port, val)                            AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x02, 0x80, 0x7, val)
#define GSV6K5_VSP_set_DG_H_POL(port, val)                            AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x02, 0x40, 0x6, val)
#define GSV6K5_VSP_set_DG_V_ACTIVE_MAN_EN(port, val)                  AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x02, 0x4, 0x2, val)
#define GSV6K5_VSP_get_DG_420_EN(port, pval)                          AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x02, 0x1, 0x0, pval)
#define GSV6K5_VSP_set_DG_420_EN(port, val)                           AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x02, 0x1, 0x0, val)
#define GSV6K5_VSP_set_DG_H_TOTAL(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x03, 0x7F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_H_ACTIVE(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x05, 0x7F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_H_FRONT(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x07, 0x7F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_H_SYNC(port, val)                           AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x09, 0x7F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_H_BACK(port, val)                           AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x0B, 0x7F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_V_TOTAL(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x0D, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_V_ACTIVE(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x0F, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_V_FRONT(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x11, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_V_SYNC(port, val)                           AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x13, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_DG_V_BACK(port, val)                           AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x15, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_set_CP_CSC_MODE(port, val)                         AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x38, 0x3, 0, val)
#define GSV6K5_VSP_get_VIN_H_TOTAL(port, pval)                        AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x52, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_H_TOTAL(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x52, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_H_ACTIVE(port, pval)                       AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x54, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_H_ACTIVE(port, val)                        AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x54, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_H_FRONT(port, pval)                        AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x56, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_H_FRONT(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x56, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_H_SYNC(port, pval)                         AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x58, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_H_SYNC(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x58, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_H_BACK(port, pval)                         AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5A, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_H_BACK(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5A, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_V_TOTAL(port, pval)                        AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5C, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_V_TOTAL(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5C, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_V_ACTIVE(port, pval)                       AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5E, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_V_ACTIVE(port, val)                        AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x5E, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_V_FRONT(port, pval)                        AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x60, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_V_FRONT(port, val)                         AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x60, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_V_SYNC(port, pval)                         AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x62, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_V_SYNC(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x62, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_VIN_V_BACK(port, pval)                         AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x64, 0x3F, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_set_VIN_V_BACK(port, val)                          AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0x64, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_CP_VID_IN(port, pval)                          AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x66, 0xFF, 0, pval)
#define GSV6K5_VSP_set_CP_VID_IN(port, val)                           AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x66, 0xFF, 0, val)
#define GSV6K5_VSP_get_CP_VIN_PARAM_MAN_EN(port, pval)                AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x68, 0x1, 0x0, pval)
#define GSV6K5_VSP_set_CP_VIN_PARAM_MAN_EN(port, val)                 AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x68, 0x1, 0x0, val)
#define GSV6K5_VSP_get_CP_VOUT_CHN_SWAP(port, pval)                   AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x78, 0x70, 4, pval)
#define GSV6K5_VSP_set_CP_VOUT_CHN_SWAP(port, val)                    AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x78, 0x70, 4, val)
#define GSV6K5_VSP_get_CP_VIN_CHN_SWAP(port, pval)                    AvHalI2cReadField8(GSV6K5_VSP_MAP_ADDR(port), 0x78, 0x7, 0, pval)
#define GSV6K5_VSP_set_CP_VIN_CHN_SWAP(port, val)                     AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0x78, 0x7, 0, val)
#define GSV6K5_VSP_set_RX1_PRBS_CHECK_EN(port, val)                   AvHalI2cWriteField8(GSV6K5_VSP_MAP_ADDR(port), 0xC1, 0x1, 0x0, val)
#define GSV6K5_VSP_set_RX1_CRC_GOLDEN(port, val)                      AvHalI2cWriteField32BE(GSV6K5_VSP_MAP_ADDR(port), 0xC2, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_VSP_get_RX1_CRC_READBACK(port, pval)                   AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0xC4, 0xFF, 0xFF, 0, 2, pval)
#define GSV6K5_VSP_get_RX1_CRC_FRAME_ERR_CNT(port, pval)              AvHalI2cReadField32BE(GSV6K5_VSP_MAP_ADDR(port), 0xC6, 0xFF, 0xFF, 0, 3, pval)
#endif
