#ifndef GSV6K5_PLL_MAP_FCT_H
#define GSV6K5_PLL_MAP_FCT_H
#define GSV6K5_PLL_set_RXA_PLL_DIV_CALC_MAN_START(port, val)          AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x10, 0x40, 0x6, val)
#define GSV6K5_PLL_set_RXA_PLL_ENABLE_MAN(port, val)                  AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x23, 0x2, 0x1, val)
#define GSV6K5_PLL_set_RXA_PLL_ENABLE_MAN_EN(port, val)               AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x23, 0x1, 0x0, val)
#define GSV6K5_PLL_get_RXA_PLL_LOCK_CAP_SEL(port, pval)               AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0x26, 0x2, 0x1, pval)
#define GSV6K5_PLL_set_RXA_PLL_LOCK_CAP_SEL(port, val)                AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x26, 0x2, 0x1, val)
#define GSV6K5_PLL_get_RB_RXA_PLL_SER_DIV(port, pval)                 AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0x2F, 0x7, 0, pval)
#define GSV6K5_PLL_get_RB_RXA_PLL_REF_PRE_DIV_FREQ(port, pval)        AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x33, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_RXA_PLL_VCO_POST_DIV_FREQ(port, pval)       AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x36, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_RXA_PLL_VCO_FREQ(port, pval)                AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x39, 0x1F, 0xFF, 0, 2, pval)
#define GSV6K5_PLL_set_TXA_PLL_DIV_CALC_MAN_START(port, val)          AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x70, 0x40, 0x6, val)
#define GSV6K5_PLL_set_TXA_PLL_ENABLE_MAN(port, val)                  AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x83, 0x2, 0x1, val)
#define GSV6K5_PLL_set_TXA_PLL_ENABLE_MAN_EN(port, val)               AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x83, 0x1, 0x0, val)
#define GSV6K5_PLL_set_TXA_PLL_LOCK_CLEAR(port, val)                  AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0x86, 0x1, 0x0, val)
#define GSV6K5_PLL_get_RB_TXA_PLL_LOCK(port, pval)                    AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0x8C, 0x80, 0x7, pval)
#define GSV6K5_PLL_get_RB_TXA_PLL_SER_DIV(port, pval)                 AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0x8F, 0x7, 0, pval)
#define GSV6K5_PLL_get_RB_TXA_PLL_REF_PRE_DIV_FREQ(port, pval)        AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x93, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_TXA_PLL_VCO_POST_DIV_FREQ(port, pval)       AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x96, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_TXA_PLL_VCO_FREQ(port, pval)                AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0x99, 0x1F, 0xFF, 0, 2, pval)
#define GSV6K5_PLL_get_RB_TXA_PLL_LOCK_CAPTURED(port, pval)           AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0x9B, 0x8, 0x3, pval)
#define GSV6K5_PLL_set_TXB_PLL_DIV_CALC_MAN_START(port, val)          AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0xA0, 0x40, 0x6, val)
#define GSV6K5_PLL_set_TXB_PLL_ENABLE_MAN(port, val)                  AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0xB3, 0x2, 0x1, val)
#define GSV6K5_PLL_set_TXB_PLL_ENABLE_MAN_EN(port, val)               AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0xB3, 0x1, 0x0, val)
#define GSV6K5_PLL_set_TXB_PLL_LOCK_CLEAR(port, val)                  AvHalI2cWriteField8(GSV6K5_PLL_MAP_ADDR(port), 0xB6, 0x1, 0x0, val)
#define GSV6K5_PLL_get_RB_TXB_PLL_LOCK(port, pval)                    AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0xBC, 0x80, 0x7, pval)
#define GSV6K5_PLL_get_RB_TXB_PLL_SER_DIV(port, pval)                 AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0xBF, 0x7, 0, pval)
#define GSV6K5_PLL_get_RB_TXB_PLL_REF_PRE_DIV_FREQ(port, pval)        AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0xC3, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_TXB_PLL_VCO_POST_DIV_FREQ(port, pval)       AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0xC6, 0x3, 0xFF, 0, 3, pval)
#define GSV6K5_PLL_get_RB_TXB_PLL_VCO_FREQ(port, pval)                AvHalI2cReadField32BE(GSV6K5_PLL_MAP_ADDR(port), 0xC9, 0x1F, 0xFF, 0, 2, pval)
#define GSV6K5_PLL_get_RB_TXB_PLL_LOCK_CAPTURED(port, pval)           AvHalI2cReadField8(GSV6K5_PLL_MAP_ADDR(port), 0xCB, 0x8, 0x3, pval)
#endif
