#ifndef GSV6K5_CP_MAP_FCT_H
#define GSV6K5_CP_MAP_FCT_H
#define GSV6K5_CP_get_CP_CSC_BYPASS(port, pval)                      AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x00, 0x20, 0x5, pval)
#define GSV6K5_CP_set_CP_LAMP_ENABLE(port, val)                      AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x00, 0x8, 0x3, val)
#define GSV6K5_CP_get_CP_OUT_QUAD_EN(port, pval)                     AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x20, 0x5, pval)
#define GSV6K5_CP_set_CP_OUT_QUAD_EN(port, val)                      AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x20, 0x5, val)
#define GSV6K5_CP_get_CP_DOWN_SCALER_H_FAC(port, pval)               AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x1C, 2, pval)
#define GSV6K5_CP_set_CP_DOWN_SCALER_H_FAC(port, val)                AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x1C, 2, val)
#define GSV6K5_CP_get_CP_DOWN_SCALER_V_FAC(port, pval)               AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x3, 0, pval)
#define GSV6K5_CP_set_CP_DOWN_SCALER_V_FAC(port, val)                AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x05, 0x3, 0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_HDR_AVERAGE_LUMA(port, val)         AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x0B, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_HDR2SDR_FORMAT(port, val)                   AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x19, 0x3, 0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_219_255_SEL(port, val)              AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x1E, 0x1, 0x0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_ONE_DIV_219(port, val)              AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x1F, 0x3F, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_HDR2SDR_Y_SDR_MAX(port, val)                AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x21, 0xF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_HDR2SDR_SDR_LUMA_RANGE(port, val)           AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x23, 0xFF, 0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_SDR_LUMA_OFFSET(port, val)          AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x24, 0xFF, 0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_IN_CH_SWAP(port, val)               AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x39, 0x70, 4, val)
#define GSV6K5_CP_set_CP_HDR2SDR_CH1_422_SEL(port, val)              AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x39, 0x8, 0x3, val)
#define GSV6K5_CP_set_CP_HDR2SDR_CH3_420_SEL(port, val)              AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x39, 0x4, 0x2, val)
#define GSV6K5_CP_set_CP_HDR2SDR_CH3_T422_SEL(port, val)             AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x39, 0x2, 0x1, val)
#define GSV6K5_CP_set_CP_HDR2SDR_CH3_422_SEL(port, val)              AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x39, 0x1, 0x0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_OUT_CH_SWAP(port, val)              AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x3A, 0x7, 0, val)
#define GSV6K5_CP_set_CP_HDR2SDR_CHROMA_CB_RATIO(port, val)          AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x3B, 0x1F, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_ANUM(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x42, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_A(port, val)                         AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x44, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_BNUM(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x46, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_B(port, val)                         AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x48, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_ANUM(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x4A, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_A(port, val)                         AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x4C, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_BNUM(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x4E, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_B(port, val)                         AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x50, 0xFF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_AMUL(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x52, 0xF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_ASHIFT(port, val)                    AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x54, 0xF, 0, val)
#define GSV6K5_CP_set_CP_LAMP_H_BMUL(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x55, 0xF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_H_BSHIFT(port, val)                    AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x57, 0xF, 0, val)
#define GSV6K5_CP_set_CP_LAMP_V_AMUL(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x58, 0xF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_ASHIFT(port, val)                    AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x5A, 0xF, 0, val)
#define GSV6K5_CP_set_CP_LAMP_V_BMUL(port, val)                      AvHalI2cWriteField32BE(GSV6K5_CP_MAP_ADDR(port), 0x5B, 0xF, 0xFF, 0, 2, val)
#define GSV6K5_CP_set_CP_LAMP_V_BSHIFT(port, val)                    AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x5D, 0xF, 0, val)
#define GSV6K5_CP_get_CP_SCALER_VOUT_H_PARAM_SEL(port, pval)         AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x61, 0x70, 4, pval)
#define GSV6K5_CP_set_CP_SCALER_VOUT_H_PARAM_SEL(port, val)          AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x61, 0x70, 4, val)
#define GSV6K5_CP_get_CP_SCALER_VOUT_V_PARAM_SEL(port, pval)         AvHalI2cReadField8(GSV6K5_CP_MAP_ADDR(port), 0x61, 0x7, 0, pval)
#define GSV6K5_CP_set_CP_SCALER_VOUT_V_PARAM_SEL(port, val)          AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0x61, 0x7, 0, val)
#define GSV6K5_CP_set_CP_VRR_EN(port, val)                           AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0xA0, 0x4, 0x2, val)
#define GSV6K5_CP_set_CP_TG_CAL_START_MAN(port, val)                 AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0xA0, 0x2, 0x1, val)
#define GSV6K5_CP_set_CP_LAMP_MODE(port, val)                        AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0xB4, 0x4, 0x2, val)
#define GSV6K5_CP_set_CP_LAMP_EN(port, val)                          AvHalI2cWriteField8(GSV6K5_CP_MAP_ADDR(port), 0xB4, 0x1, 0x0, val)
#endif
